# this class will only install the puppet-salt master
# example:
# class { 'puppet-salt::master': }
#
class puppet-salt::master (
  $repo_file_manage                       = $puppet-salt::params::repo_file_manage,
  $repo_file                              = $puppet-salt::params::repo_file,
  $repo_file_template                     = $puppet-salt::params::repo_file_template,
  $master_config_manage                   = $puppet-salt::params::master_config_manage,
  $master_config                          = $puppet-salt::params::master_config,
  $master_config_template                 = $puppet-salt::params::master_config_template,
  $master_package_name                    = $puppet-salt::params::master_package_name,
  $master_package_ensure                  = $puppet-salt::params::master_package_ensure,
  $master_service_name                    = $puppet-salt::params::master_service_name,
  $master_service_ensure                  = $puppet-salt::params::master_service_ensure,
  $master_service_manage                  = $puppet-salt::params::master_service_manage,
  $master_service_enable                  = $puppet-salt::params::master_service_enable,
  $master_default_include                 = $puppet-salt::params::master_default_include,
  $master_interface                       = $puppet-salt::params::master_interface,
  $master_ipv6                            = $puppet-salt::params::master_ipv6,
  $master_publish_port                    = $puppet-salt::params::master_publish_port,
  $master_user                            = $puppet-salt::params::master_user,
  $master_max_open_files                  = $puppet-salt::params::master_max_open_files,
  $master_worker_threads                  = $puppet-salt::params::master_worker_threads,
  $master_ret_port                        = $puppet-salt::params::master_ret_port,
  $master_pid_file                        = $puppet-salt::params::master_pid_file,
  $master_root_dir                        = $puppet-salt::params::master_root_dir,
  $master_pki_dir                         = $puppet-salt::params::master_pki_dir,
  $master_cachedir                        = $puppet-salt::params::master_cachedir,
  $master_extension_modules               = $puppet-salt::params::master_extension_modules,
  $master_verify_env                      = $puppet-salt::params::master_verify_env,
  $master_keep_jobs                       = $puppet-salt::params::master_keep_jobs,
  $master_timeout                         = $puppet-salt::params::master_timeout,
  $master_loop_interval                   = $puppet-salt::params::master_loop_interval,
  $master_output                          = $puppet-salt::params::master_output,
  $master_show_timeout                    = $puppet-salt::params::master_show_timeout,
  $master_color                           = $puppet-salt::params::master_color,
  $master_strip_colors                    = $puppet-salt::params::master_strip_colors,
  $master_sock_dir                        = $puppet-salt::params::master_sock_dir,
  $master_enable_gpu_grains               = $puppet-salt::params::master_enable_gpu_grains,
  $master_job_cache                       = $puppet-salt::params::master_job_cache,
  $master_minion_data_cache               = $puppet-salt::params::master_minion_data_cache,
  $master_event_return                    = $puppet-salt::params::master_event_return,
  $master_event_return_queue              = $puppet-salt::params::master_event_return_queue,
  $master_event_return_whitelist          = $puppet-salt::params::master_event_return_whitelist,
  $master_event_return_blacklist          = $puppet-salt::params::master_event_return_blacklist,
  $master_max_event_size                  = $puppet-salt::params::master_max_event_size,
  $master_ping_on_rotate                  = $puppet-salt::params::master_ping_on_rotate,
  $master_preserve_minion_cache           = $puppet-salt::params::master_preserve_minion_cache,
  $master_con_cache                       = $puppet-salt::params::master_con_cache,
  $master_open_mode                       = $puppet-salt::params::master_open_mode,
  $master_auto_accept                     = $puppet-salt::params::master_auto_accept,
  $master_autosign_timeout                = $puppet-salt::params::master_autosign_timeout,
  $master_autosign_file                   = $puppet-salt::params::master_autosign_file,
  $master_autoreject_file                 = $puppet-salt::params::master_autoreject_file,
  $master_permissive_pki_access           = $puppet-salt::params::master_permissive_pki_access,
  $master_client_acl                      = $puppet-salt::params::master_client_acl,
  $master_client_acl_blacklist            = $puppet-salt::params::master_client_acl_blacklist,
  $master_sudo_acl                        = $puppet-salt::params::master_sudo_acl,
  $master_external_auth                   = $puppet-salt::params::master_external_auth,
  $master_token_expire                    = $puppet-salt::params::master_token_expire,
  $master_file_recv                       = $puppet-salt::params::master_file_recv,
  $master_file_recv_max_size              = $puppet-salt::params::master_file_recv_max_size,
  $master_sign_pub_messages               = $puppet-salt::params::master_sign_pub_messages,
  $master_roster_file                     = $puppet-salt::params::master_roster_file,
  $master_ssh_minion_opts                 = $puppet-salt::params::master_ssh_minion_opts,
  $master_runner_dirs                     = $puppet-salt::params::master_runner_dirs,
  $master_cython_enable                   = $puppet-salt::params::master_cython_enable,
  $master_state_top                       = $puppet-salt::params::master_state_top,
  $master_master_tops                     = $puppet-salt::params::master_master_tops,
  $master_external_nodes                  = $puppet-salt::params::master_external_nodes,
  $master_renderer                        = $puppet-salt::params::master_renderer,
  $master_jinja_trim_blocks               = $puppet-salt::params::master_jinja_trim_blocks,
  $master_jinja_lstrip_blocks             = $puppet-salt::params::master_jinja_lstrip_blocks,
  $master_failhard                        = $puppet-salt::params::master_failhard,
  $master_state_verbose                   = $puppet-salt::params::master_state_verbose,
  $master_state_output                    = $puppet-salt::params::master_state_output,
  $master_state_aggregate                 = $puppet-salt::params::master_state_aggregate,
  $master_state_events                    = $puppet-salt::params::master_state_events,
  $master_file_roots                      = $puppet-salt::params::master_file_roots,
  $master_top_file_merging_strategy       = $puppet-salt::params::master_top_file_merging_strategy,
  $master_env_order                       = $puppet-salt::params::master_env_order,
  $master_default_top                     = $puppet-salt::params::master_default_top,
  $master_hash_type                       = $puppet-salt::params::master_hash_type,
  $master_file_buffer_size                = $puppet-salt::params::master_file_buffer_size,
  $master_file_ignore_regex               = $puppet-salt::params::master_file_ignore_regex,
  $master_file_ignore_glob                = $puppet-salt::params::master_file_ignore_glob,
  $master_fileserver_backend              = $puppet-salt::params::master_fileserver_backend,
  $master_fileserver_followsymlinks       = $puppet-salt::params::master_fileserver_followsymlinks,
  $master_fileserver_ignoresymlinks       = $puppet-salt::params::master_fileserver_ignoresymlinks,
  $master_fileserver_limit_traversal      = $puppet-salt::params::master_fileserver_limit_traversal,
  $master_gitfs_remotes                   = $puppet-salt::params::master_gitfs_remotes,
  $master_gitfs_ssl_verify                = $puppet-salt::params::master_gitfs_ssl_verify,
  $master_gitfs_root                      = $puppet-salt::params::master_gitfs_root,
  $master_pillar_roots                    = $puppet-salt::params::master_pillar_roots,
  $master_ext_pillar                      = $puppet-salt::params::master_ext_pillar,
  $master_pillar_opts                     = $puppet-salt::params::master_pillar_opts,
  $master_pillar_safe_render_error        = $puppet-salt::params::master_pillar_safe_render_error,
  $master_pillar_source_merging_strategy  = $puppet-salt::params::master_pillar_source_merging_strategy,
  $master_order_masters                   = $puppet-salt::params::master_order_masters,
  $master_syndic_master                   = $puppet-salt::params::master_syndic_master,
  $master_peer                            = $puppet-salt::params::master_peer,
  $master_log_file                        = $puppet-salt::params::master_log_file,
  $master_key_logfile                     = $puppet-salt::params::master_key_logfile,
  $master_log_level                       = $puppet-salt::params::master_log_level,
  $master_log_level_logfile               = $puppet-salt::params::master_log_level_logfile,
  $master_log_datefmt                     = $puppet-salt::params::master_log_datefmt,
  $master_log_datefmt_logfile             = $puppet-salt::params::master_log_datefmt_logfile,
  $master_log_fmt_logfile                 = $puppet-salt::params::master_log_fmt_logfile,
  $master_log_granular_levels             = $puppet-salt::params::master_log_granular_levels,
  $master_nodegroups                      = $puppet-salt::params::master_nodegroups,
  $master_range_server                    = $puppet-salt::params::master_range_server,)
inherits puppet-salt::params {
  include 'puppet-salt::master::install'
  include 'puppet-salt::master::config'
  include 'puppet-salt::master::service'

  # Anchor this as per #8140 - this ensures that classes won't float off and
  # mess everything up.  You can read about this at:
  # http://docs.puppetlabs.com/puppet/2.7/reference/lang_containment.html#known-issues
  anchor { 'puppet-salt::master::begin': }
  anchor { 'puppet-salt::master::end': }

  Anchor['puppet-salt::master::begin'] ->
    Class['puppet-salt::master::install'] ->
    Class['puppet-salt::master::config'] ->
    Class['puppet-salt::master::service'] ->
  Anchor['puppet-salt::master::end']

}
