# this class will only install the puppet-salt minion
# example:
# class { 'puppet-salt::minion': }
#
class puppet-salt::minion (
  $repo_file_manage                   = $puppet-salt::params::repo_file_manage,
  $repo_file                          = $puppet-salt::params::repo_file,
  $repo_file_template                 = $puppet-salt::params::repo_file_template,
  $minion_config_manage               = $puppet-salt::params::minion_config_manage,
  $minion_config                      = $puppet-salt::params::minion_config,
  $minion_config_template             = $puppet-salt::params::minion_config_template,
  $minion_package_name                = $puppet-salt::params::minion_package_name,
  $minion_package_ensure              = $puppet-salt::params::minion_package_ensure,
  $minion_service_name                = $puppet-salt::params::minion_service_name,
  $minion_service_ensure              = $puppet-salt::params::minion_service_ensure,
  $minion_service_manage              = $puppet-salt::params::minion_service_manage,
  $minion_service_enable              = $puppet-salt::params::minion_service_enable,
  $minion_default_include             = $puppet-salt::params::minion_default_include,
  $minion_master                      = $puppet-salt::params::minion_master,
  $minion_random_master               = $puppet-salt::params::minion_random_master,
  $minion_master_type                 = $puppet-salt::params::minion_master_type,
  $minion_master_alive_interval       = $puppet-salt::params::minion_master_alive_interval,
  $minion_ipv6                        = $puppet-salt::params::minion_ipv6,
  $minion_retry_dns                   = $puppet-salt::params::minion_retry_dns,
  $minion_master_port                 = $puppet-salt::params::minion_master_port,
  $minion_user                        = $puppet-salt::params::minion_user,
  $minion_sudo_user                   = $puppet-salt::params::minion_sudo_user,
  $minion_pidfile                     = $puppet-salt::params::minion_pidfile,
  $minion_root_dir                    = $puppet-salt::params::minion_root_dir,
  $minion_pki_dir                     = $puppet-salt::params::minion_pki_dir,
  $minion_id                          = $puppet-salt::params::minion_id,
  $minion_append_domain               = $puppet-salt::params::minion_append_domain,
  $minion_cachedir                    = $puppet-salt::params::minion_cachedir,
  $minion_verify_env                  = $puppet-salt::params::minion_verify_env,
  $minion_cache_jobs                  = $puppet-salt::params::minion_cache_jobs,
  $minion_sock_dir                    = $puppet-salt::params::minion_sock_dir,
  $minion_output                      = $puppet-salt::params::minion_output,
  $minion_color                       = $puppet-salt::params::minion_color,
  $minion_strip_colors                = $puppet-salt::params::minion_strip_colors,
  $minion_backup_mode                 = $puppet-salt::params::minion_backup_mode,
  $minion_acceptance_wait_time        = $puppet-salt::params::minion_acceptance_wait_time,
  $minion_acceptance_wait_time_max    = $puppet-salt::params::minion_acceptance_wait_time_max,
  $minion_rejected_retry              = $puppet-salt::params::minion_rejected_retry,
  $minion_random_reauth_delay         = $puppet-salt::params::minion_random_reauth_delay,
  $minion_auth_timeout                = $puppet-salt::params::minion_auth_timeout,
  $minion_auth_tries                  = $puppet-salt::params::minion_auth_tries,
  $minion_auth_safemode               = $puppet-salt::params::minion_auth_safemode,
  $minion_ping_interval               = $puppet-salt::params::minion_ping_interval,
  $minion_recon_default               = $puppet-salt::params::minion_recon_default,
  $minion_recon_max                   = $puppet-salt::params::minion_recon_max,
  $minion_recon_randomize             = $puppet-salt::params::minion_recon_randomize,
  $minion_loop_interval               = $puppet-salt::params::minion_loop_interval,
  $minion_grains_refresh_every        = $puppet-salt::params::minion_grains_refresh_every,
  $minion_grains_cache                = $puppet-salt::params::minion_grains_cache,
  $minion_grains_cache_expiration     = $puppet-salt::params::minion_grains_cache_expiration,
  $minion_ipc_mode                    = $puppet-salt::params::minion_ipc_mode,
  $minion_tcp_pub_port                = $puppet-salt::params::minion_tcp_pub_port,
  $minion_tcp_pull_port               = $puppet-salt::params::minion_tcp_pull_port,
  $minion_max_event_size              = $puppet-salt::params::minion_max_event_size,
  $minion_disable_modules             = $puppet-salt::params::minion_disable_modules,
  $minion_disable_returners           = $puppet-salt::params::minion_disable_returners,
  $minion_module_dirs                 = $puppet-salt::params::minion_module_dirs,
  $minion_returner_dirs               = $puppet-salt::params::minion_returner_dirs,
  $minion_states_dirs                 = $puppet-salt::params::minion_states_dirs,
  $minion_render_dirs                 = $puppet-salt::params::minion_render_dirs,
  $minion_utils_dirs                  = $puppet-salt::params::minion_utils_dirs,
  $minion_providers                   = $puppet-salt::params::minion_providers,
  $minion_cython_enable               = $puppet-salt::params::minion_cython_enable,
  $minion_modules_max_memory          = $puppet-salt::params::minion_modules_max_memory,
  $minion_renderer                    = $puppet-salt::params::minion_renderer,
  $minion_failhard                    = $puppet-salt::params::minion_failhard,
  $minion_autoload_dynamic_modules    = $puppet-salt::params::minion_autoload_dynamic_modules,
  $minion_clean_dynamic_modules       = $puppet-salt::params::minion_clean_dynamic_modules,
  $minion_environment                 = $puppet-salt::params::minion_environment,
  $minion_state_top                   = $puppet-salt::params::minion_state_top,
  $minion_startup_states              = $puppet-salt::params::minion_startup_states,
  $minion_sls_list                    = $puppet-salt::params::minion_sls_list,
  $minion_top_file                    = $puppet-salt::params::minion_top_file,
  $minion_state_aggregate             = $puppet-salt::params::minion_state_aggregate,
  $minion_file_client                 = $puppet-salt::params::minion_file_client,
  $minion_file_roots                  = $puppet-salt::params::minion_file_roots,
  $minion_fileserver_limit_traversal  = $puppet-salt::params::minion_fileserver_limit_traversal,
  $minion_hash_type                   = $puppet-salt::params::minion_hash_type,
  $minion_pillar_roots                = $puppet-salt::params::minion_pillar_roots,
  $minion_open_mode                   = $puppet-salt::params::minion_open_mode,
  $minion_permissive_pki_access       = $puppet-salt::params::minion_permissive_pki_access,
  $minion_state_verbose               = $puppet-salt::params::minion_state_verbose,
  $minion_state_output                = $puppet-salt::params::minion_state_output,
  $minion_state_output_diff           = $puppet-salt::params::minion_state_output_diff,
  $minion_state_output_profile        = $puppet-salt::params::minion_state_output_profile,
  $minion_master_finger               = $puppet-salt::params::minion_master_finger,
  $minion_multiprocessing             = $puppet-salt::params::minion_multiprocessing,
  $minion_log_file                    = $puppet-salt::params::minion_log_file,
  $minion_key_logfile                 = $puppet-salt::params::minion_key_logfile,
  $minion_log_level                   = $puppet-salt::params::minion_log_level,
  $minion_log_level_logfile           = $puppet-salt::params::minion_log_level_logfile,
  $minion_log_datefmt                 = $puppet-salt::params::minion_log_datefmt,
  $minion_log_datefmt_logfile         = $puppet-salt::params::minion_log_datefmt_logfile,
  $minion_log_fmt_console             = $puppet-salt::params::minion_log_fmt_console,
  $minion_log_fmt_logfile             = $puppet-salt::params::minion_log_fmt_logfile,
  $minion_log_granular_levels         = $puppet-salt::params::minion_log_granular_levels,
  $minion_zmq_monitor                 = $puppet-salt::params::minion_zmq_monitor,
  $minion_test                        = $puppet-salt::params::minion_test,
  $minion_update_url                  = $puppet-salt::params::minion_update_url,
  $minion_update_restart_services     = $puppet-salt::params::minion_update_restart_services,
  $minion_tcp_keepalive               = $puppet-salt::params::minion_tcp_keepalive,
  $minion_tcp_keepalive_idle          = $puppet-salt::params::minion_tcp_keepalive_idle,
  $minion_tcp_keepalive_cnt           = $puppet-salt::params::minion_tcp_keepalive_cnt,)
inherits puppet-salt::params {
  include 'puppet-salt::minion::install'
  include 'puppet-salt::minion::config'
  include 'puppet-salt::minion::service'

  # Anchor this as per #8140 - this ensures that classes won't float off and
  # mess everything up.  You can read about this at:
  # http://docs.puppetlabs.com/puppet/2.7/reference/lang_containment.html#known-issues
  anchor { 'puppet-salt::minion::begin': }
  anchor { 'puppet-salt::minion::end': }

  Anchor['puppet-salt::minion::begin'] ->
    Class['puppet-salt::minion::install'] ->
    Class['puppet-salt::minion::config'] ->
    Class['puppet-salt::minion::service'] ->
  Anchor['puppet-salt::minion::end']
}
